# {
#  "semi": true,
#   "singleQuote": true,
#   "trailingComma": "es5",
#   "printWidth": 80,
#  "tabWidth": 2,
#  "useTabs": false
# }
parser: 'typescript'
useTabs: false
tabWidth: 2
singleQuote: true
printWidth: 110
bracketSpacing: true
semi: true
endOfLine: 'lf'
proseWrap: never
arrowParens: avoid
