name: Publish  Release

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  Publish-NPM-Package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: |
          rm -f pnpm-lock.yaml
          pnpm install --no-frozen-lockfile

      - name: Run test Anilist
        run: pnpm test-anilist

      - name: Run test Jikan
        run: pnpm test-jikan

      - name: Run test Hianime
        run: pnpm test-hianime
      
      - name: Run test Animekai
        run: pnpm test-animekai
      
      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build
  
      - name: Publish to NPM
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
