name: Publish Release # Consistent capitalization for clarity

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  run-tests: # Job names should be kebab-case for consistency
    name: Run Tests # More descriptive name for the job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures full history for tools like semantic-release if used later

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          # registry-url is not needed here unless you're installing from a private registry
          # but harmless if left for consistency with publish job

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: |
          # The 'rm -f pnpm-lock.yaml' and '--no-frozen-lockfile' are generally
          # discouraged in CI unless you specifically know why you need them.
          # For reproducible builds, you typically want to use the lockfile.
          # If you *must* delete it, ensure it's intentional.
          # For typical install, just 'pnpm install' is enough.
          # I'm keeping your original logic for now, but consider removing rm -f.
          # rm -f pnpm-lock.yaml # Consider removing this line for reproducible builds
          pnpm install --no-frozen-lockfile

      - name: Run test Anilist
        run: pnpm test-anilist

      - name: Run test Jikan
        run: pnpm test-jikan

      - name: Run test Hianime
        run: pnpm test-hianime

      # Uncomment if you want to run this test
      # - name: Run test Animekai
      #   run: pnpm test-animekai

      - name: Lint
        run: pnpm lint


  publish-npm-package: # Corrected indentation and kebab-case name
    name: Publish NPM Package
    runs-on: ubuntu-latest
    needs: run-tests # This is crucial: ensures tests pass before attempting to publish
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org' # Essential for publishing to NPM
       

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: |
          # Again, consider removing 'rm -f' if you want reproducible builds.
          # rm -f pnpm-lock.yaml
          pnpm install --no-frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Publish to NPM
        run: pnpm semantic-release
        # env:
          # NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}