name: Publish Release 

on:
  workflow_dispatch:

jobs:
  run-tests: 
    name: Run Tests 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Run test Anilist
        run: pnpm test-anilist

      - name: Run test Jikan
        run: pnpm test-jikan

      - name: Run test Hianime
        run: pnpm test-hianime

      
      # - name: Run test Animekai
      #   run: pnpm test-animekai

      - name: Lint
        run: pnpm lint


  publish-npm-package: # Corrected indentation and kebab-case name
    name: Publish NPM Package
    runs-on: ubuntu-latest
    needs: run-tests 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org' 
       

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: |
         
          pnpm install --no-frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Publish to NPM
        run: pnpm semantic-release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}   #PROBLEMS COULD ARISE HERE IT COULD BE NPM_TOKEN
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}