name: Create Release

on:
  workflow_dispatch:  # Allow manual triggering

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  

      - name: Ensure jq is installed
        run: sudo apt-get install -y jq

      - name: Extract version from package.json
        id: version
        run: |
          NEW_VERSION=$(jq -r .version package.json)
          echo "Current version in package.json: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_ENV

      - name: Extract latest version from CHANGELOG.md
        id: changelog_version
        run: |
          CHANGELOG_VERSION=$(awk -F '[][]' '/^## \[/{print $2; exit}' CHANGELOG.md)
          echo "Latest version in CHANGELOG.md: $CHANGELOG_VERSION"
          echo "changelog_version=$CHANGELOG_VERSION" >> $GITHUB_ENV

      - name: Bump package.json version to match CHANGELOG.md (if needed)
        id: bump_version
        run: |
          if [ "$NEW_VERSION" != "$CHANGELOG_VERSION" ]; then
            echo "Version mismatch detected! Updating package.json..."
            jq --arg new_version "$CHANGELOG_VERSION" '.version = $new_version' package.json > temp.json && mv temp.json package.json
            echo "Updated package.json to version $CHANGELOG_VERSION"
            echo "new_version=$CHANGELOG_VERSION" >> $GITHUB_ENV
          else
            echo "Versions match! No update needed."
          fi

      - name: Commit updated package.json (if version was bumped)
        if: env.new_version != env.version
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add package.json
          git commit -m "Bump version to $CHANGELOG_VERSION [skip ci]"
          git tag v$CHANGELOG_VERSION
          git push origin v$CHANGELOG_VERSION
          git push

      - name: Extract release notes from CHANGELOG.md
        id: changelog
        run: |
          RELEASE_NOTES=$(awk -v version="[$CHANGELOG_VERSION]" '/^## / {if ($2 ~ version) {flag=1; next} else {flag=0}} flag' CHANGELOG.md)
          echo "Release notes: $RELEASE_NOTES"
          echo "release_notes<<EOF" >> $GITHUB_ENV
          echo "$RELEASE_NOTES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ env.new_version }}
          release_name: Release v${{ env.new_version }}
          body: ${{ env.release_notes }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
